export const UI = {
  app: {
    name: "RASMA",
    description: "Sistema de Gestión de Consulta Terapéutica",
    tagline: "Especialistas en TEA y Salud Mental",
  },
  nav: {
    dashboard: "Panel",
    patients: "Pacientes",
    appointments: "Citas",
    payments: "Pagos",
    notes: "Notas de Sesión",
    plans: "Planes de Tratamiento",
    reports: "Reportes",
    settings: "Configuración",
    users: "Usuarios",
    calendar: "Calendario",
    team: "Equipo",
    chat: "Mensajes",
    profile: "Mi Perfil",
    auditLog: "Registro de Auditoría",
    logout: "Cerrar Sesión",
    rrhh: "RRHH",
    myAppointments: "Mis Citas",
    pending: "Pendiente",
    expenses: "Gastos",
    finances: "Finanzas",
    income: "Ingresos",
    documents: "Documentos",
  },
  auth: {
    login: "Iniciar Sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    currentPassword: "Contraseña actual",
    newPassword: "Nueva contraseña",
    confirmPassword: "Confirmar contraseña",
    loginButton: "Entrar",
    loginError: "Credenciales inválidas. Intente de nuevo.",
    loginLocked:
      "Demasiados intentos fallidos. Intente de nuevo en 15 minutos.",
    welcome: "Bienvenido a RASMA",
    welcomeSubtitle: "Sistema de Gestión Clínica",
    loginWithGoogle: "Continuar con Google",
    orContinueWith: "o continuar con correo",
    forgotPassword: "¿Olvidó su contraseña?",
    resetPassword: "Restablecer Contraseña",
    resetPasswordSent:
      "Si el correo existe en nuestro sistema, recibirá un enlace para restablecer su contraseña.",
    resetPasswordButton: "Enviar enlace de recuperación",
    newPasswordButton: "Establecer nueva contraseña",
    passwordChanged: "Contraseña actualizada exitosamente.",
    tokenExpired:
      "El enlace de recuperación ha expirado. Solicite uno nuevo.",
    tokenInvalid: "El enlace de recuperación no es válido.",
    backToLogin: "Volver al inicio de sesión",
  },
  profile: {
    title: "Mi Perfil",
    changeName: "Cambiar nombre",
    changeEmail: "Cambiar correo electrónico",
    changePassword: "Cambiar contraseña",
    emailChangeRequested:
      "Se envió un correo de verificación a su nueva dirección.",
    emailChanged: "Correo electrónico actualizado.",
    passwordRequiredForEmail:
      "Ingrese su contraseña actual para cambiar el correo.",
  },
  patients: {
    title: "Pacientes",
    newPatient: "Nuevo Paciente",
    editPatient: "Editar Paciente",
    patientDetail: "Detalle del Paciente",
    firstName: "Nombre",
    lastName: "Apellido",
    rut: "RUT",
    email: "Correo electrónico",
    phone: "Teléfono",
    dateOfBirth: "Fecha de Nacimiento",
    gender: "Género",
    genders: {
      masculino: "Masculino",
      femenino: "Femenino",
      otro: "Otro",
      no_especificado: "No especificado",
    },
    address: "Dirección",
    emergencyContact: "Contacto de Emergencia",
    emergencyContactName: "Nombre del Contacto",
    emergencyContactPhone: "Teléfono del Contacto",
    emergencyContactRelation: "Relación",
    insurance: "Seguro Médico",
    insuranceNumber: "Número de Póliza",
    referralSource: "Fuente de Referencia",
    therapist: "Terapeuta Asignado",
    status: "Estado",
    statuses: {
      activo: "Activo",
      inactivo: "Inactivo",
      alta: "Alta",
    },
    types: {
      fundacion: "Fundación",
      externo: "Externo",
    } as Record<string, string>,
    notes: "Notas",
    noPatients: "No hay pacientes registrados.",
    searchPlaceholder: "Buscar por nombre, RUT o correo...",
    created: "Paciente creado exitosamente.",
    updated: "Paciente actualizado exitosamente.",
    deleted: "Paciente eliminado exitosamente.",
    confirmDelete: "¿Está seguro de que desea eliminar este paciente?",
    tabInfo: "Información",
    tabAppointments: "Citas",
    tabPayments: "Pagos",
    tabNotes: "Notas Clínicas",
    tabPlans: "Planes",
  },
  appointments: {
    title: "Citas",
    new: "Nueva Cita",
    edit: "Editar Cita",
    dateTime: "Fecha y Hora",
    duration: "Duración (minutos)",
    sessionType: "Tipo de Sesión",
    sessionTypes: {
      individual: "Individual",
      pareja: "Pareja",
      familiar: "Familiar",
      grupal: "Grupal",
      evaluacion: "Evaluación",
    },
    modality: "Modalidad",
    modalities: {
      presencial: "Presencial",
      online: "Online",
    },
    location: "Ubicación",
    meetingLink: "Enlace de Reunión",
    statuses: {
      programada: "Programada",
      completada: "Completada",
      cancelada: "Cancelada",
      no_asistio: "No Asistió",
    },
  },
  payments: {
    title: "Pagos",
    new: "Nuevo Pago",
    amount: "Monto",
    method: "Método de Pago",
    methods: {
      efectivo: "Efectivo",
      transferencia: "Transferencia",
      tarjeta: "Tarjeta",
      mercadopago: "MercadoPago",
      otro: "Otro",
    },
    receipt: "Número de Recibo",
    statuses: {
      pendiente: "Pendiente",
      pagado: "Pagado",
      parcial: "Parcial",
      cancelado: "Cancelado",
    },
  },
  expenses: {
    title: "Gastos",
    new: "Nuevo Gasto",
    description: "Descripción",
    amount: "Monto",
    category: "Categoría",
    date: "Fecha",
    receipt: "Comprobante",
    notes: "Notas",
    categories: {
      all: "Todas",
      arriendo: "Arriendo",
      servicios_basicos: "Servicios Básicos",
      suministros: "Suministros",
      mantenimiento: "Mantenimiento",
      seguros: "Seguros",
      marketing: "Marketing",
      software: "Software",
      personal: "Personal",
      otros: "Otros",
    } as Record<string, string>,
  },
  expensePresets: [
    { label: "Arriendo oficina", category: "arriendo" },
    { label: "Electricidad", category: "servicios_basicos" },
    { label: "Agua", category: "servicios_basicos" },
    { label: "Internet", category: "servicios_basicos" },
    { label: "Gas", category: "servicios_basicos" },
    { label: "Material de oficina", category: "suministros" },
    { label: "Insumos clínicos", category: "suministros" },
    { label: "Artículos de limpieza", category: "suministros" },
    { label: "Reparación equipos", category: "mantenimiento" },
    { label: "Limpieza oficina", category: "mantenimiento" },
    { label: "Seguro de responsabilidad", category: "seguros" },
    { label: "Publicidad redes sociales", category: "marketing" },
    { label: "Diseño gráfico", category: "marketing" },
    { label: "Licencia software", category: "software" },
    { label: "Hosting / dominio", category: "software" },
    { label: "Evaluación Ados-2", category: "personal" },
    { label: "Pago sesión sin contrato", category: "personal" },
    { label: "Honorarios profesional", category: "personal" },
  ] as { label: string; category: string }[],
  income: {
    title: "Ingresos",
    new: "Nuevo Ingreso",
    description: "Descripción",
    amount: "Monto",
    category: "Categoría",
    date: "Fecha",
    donorName: "Nombre del Donante",
    referenceNumber: "N° de Referencia",
    receipt: "Comprobante",
    notes: "Notas",
    categories: {
      all: "Todas",
      donacion: "Donación",
      subvencion: "Subvención",
      patrocinio: "Patrocinio",
      evento_benefico: "Evento Benéfico",
      convenio: "Convenio",
      otro_ingreso: "Otro Ingreso",
    } as Record<string, string>,
  },
  incomePresets: [
    { label: "Donación particular", category: "donacion" },
    { label: "Donación empresa", category: "donacion" },
    { label: "Subvención municipal", category: "subvencion" },
    { label: "Subvención SENADIS", category: "subvencion" },
    { label: "Subvención SENAME", category: "subvencion" },
    { label: "Patrocinio corporativo", category: "patrocinio" },
    { label: "Rifa benéfica", category: "evento_benefico" },
    { label: "Gala anual", category: "evento_benefico" },
    { label: "Colecta", category: "evento_benefico" },
    { label: "Convenio colegio", category: "convenio" },
    { label: "Convenio centro salud", category: "convenio" },
    { label: "Intereses bancarios", category: "otro_ingreso" },
  ] as { label: string; category: string }[],
  finance: {
    title: "Finanzas",
    subtitle: "Resumen Financiero",
    totalIncome: "Ingresos Totales",
    totalExpenses: "Gastos Totales",
    netBalance: "Balance Neto",
    cashPosition: "Posición de Caja",
    initialBalance: "Saldo Inicial",
    editInitialBalance: "Editar Saldo Inicial",
    incomeBreakdown: "Desglose de Ingresos",
    expenseBreakdown: "Desglose de Gastos",
    monthlyTrend: "Tendencia Mensual",
    patientPayments: "Pagos de Pacientes",
    receiptCompliance: "Cumplimiento de Comprobantes",
    vsLastPeriod: "vs período anterior",
    periods: {
      month: "Mes",
      quarter: "Trimestre",
      semester: "Semestre",
      year: "Año",
    } as Record<string, string>,
  },
  users: {
    title: "Gestión de Usuarios",
    newUser: "Nuevo Usuario",
    editUser: "Editar Usuario",
    role: "Rol",
    roles: {
      admin: "Administrador",
      terapeuta: "Terapeuta",
      recepcionista: "Recepcionista",
      supervisor: "Supervisor",
      rrhh: "Recursos Humanos",
      paciente: "Paciente",
      invitado: "Invitado",
    },
    active: "Activo",
    inactive: "Inactivo",
    resetPassword: "Restablecer Contraseña",
    created: "Usuario creado exitosamente.",
    updated: "Usuario actualizado exitosamente.",
    deactivated: "Usuario desactivado.",
    confirmRemove: "¿Está seguro de que desea eliminar este usuario? Se desactivará su cuenta, se desasignará como terapeuta de sus pacientes y se removerá de equipos de atención.",
    removed: "Usuario eliminado exitosamente.",
  },
  professionals: {
    title: "Equipo Profesional",
    subtitle: "Un equipo interdisciplinario, especializado y comprometido contigo",
    specialty: "Especialidad",
    area: "Área",
    attentionType: "Atención",
    status: "Estado",
    areas: {
      clinica: "Clínica",
      salud_mental: "Salud Mental",
      atencion_directa: "Atención Directa",
      neurodesarrollo: "Neurodesarrollo",
      lenguaje: "Lenguaje",
      product: "Product",
    } as Record<string, string>,
    statuses: {
      evaluando: "Evaluando",
      disponible: "Disponible",
      completo: "Completo",
    },
  },
  chat: {
    title: "Mensajes",
    newMessage: "Nuevo mensaje",
    noMessages: "Sin mensajes",
    careTeam: "Equipo de Atención",
    sendMessage: "Enviar mensaje",
    placeholder: "Escribe un mensaje...",
  },
  notifications: {
    title: "Notificaciones",
    markAllRead: "Marcar todo como leído",
    empty: "Sin notificaciones",
    appointmentReminder: "Recordatorio de cita",
    newMessage: "Nuevo mensaje",
    statusChange: "Cambio de estado",
  },
  bulk: {
    selected: "seleccionados",
    changeRole: "Cambiar rol",
    changeArea: "Cambiar área",
    changeStatus: "Cambiar estado",
    assignTherapist: "Asignar terapeuta",
    noTherapist: "Sin terapeuta",
    deactivate: "Desactivar",
    bulkSuccess: "pacientes actualizados",
    deselect: "Deseleccionar",
  },
  common: {
    loading: "Cargando...",
    error: "Ocurrió un error. Intente de nuevo.",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    search: "Buscar",
    actions: "Acciones",
    confirm: "Confirmar",
    back: "Volver",
    noResults: "Sin resultados.",
    showing: "Mostrando",
    of: "de",
    page: "Página",
    previous: "Anterior",
    next: "Siguiente",
    required: "Este campo es obligatorio.",
    invalidEmail: "Correo electrónico inválido.",
    passwordMinLength: "La contraseña debe tener al menos 8 caracteres.",
    passwordsNoMatch: "Las contraseñas no coinciden.",
    unauthorized: "No tiene permisos para realizar esta acción.",
    yes: "Sí",
    no: "No",
    date: "Fecha",
    createdAt: "Fecha de Creación",
  },
  documents: {
    rename: "Renombrar",
    editLabel: "Editar etiqueta",
    changeCategory: "Cambiar categoría",
    labelPlaceholder: "Ej: Informe TEA, Evaluación Cognitiva...",
    searchPlaceholder: "Buscar por nombre o etiqueta...",
    categories: {
      all: "Todas",
      general: "General",
      evaluacion: "Evaluación",
      informe: "Informe",
      consentimiento: "Consentimiento",
      otro: "Otro",
    } as Record<string, string>,
    defaultLabels: [
      "Informe TEA",
      "Evaluación Cognitiva",
      "Consentimiento Informado",
      "Informe Psicológico",
      "Plan de Intervención",
      "Informe Escolar",
      "Derivación Médica",
      "Anamnesis",
    ],
  },
  rrhh: {
    title: "Recursos Humanos",
    subtitle: "Gestión de personal y postulaciones",
    applicants: "Postulantes",
    team: "Equipo",
    evaluations: "Evaluaciones",
    benefits: "Beneficios",
    statuses: {
      nuevo: "Nuevo",
      en_revision: "En revisión",
      entrevista: "Entrevista",
      aceptado: "Aceptado",
      rechazado: "Rechazado",
      en_espera: "En espera",
    } as Record<string, string>,
    noApplicants: "No hay postulantes registrados.",
    searchPlaceholder: "Buscar postulantes...",
    addNote: "Agregar nota",
    sendEmail: "Enviar correo",
    changeStatus: "Cambiar estado",
    staffDocCategories: {
      all: "Todas",
      cv: "CV",
      contrato: "Contrato",
      certificacion: "Certificación",
      evaluacion: "Evaluación",
      otro: "Otro",
    } as Record<string, string>,
    staffDocDefaultLabels: [
      "CV Actualizado",
      "Contrato Vigente",
      "Certificado de Título",
      "Registro SIS",
      "Certificado de Antecedentes",
      "Acuerdo de Confidencialidad",
      "Evaluación de Desempeño",
      "Licencia Médica",
    ],
    benefitTypes: {
      salud: "Salud",
      transporte: "Transporte",
      alimentacion: "Alimentación",
      capacitacion: "Capacitación",
      otro: "Otro",
    } as Record<string, string>,
    evalStatuses: {
      borrador: "Borrador",
      completada: "Completada",
      revisada: "Revisada",
    } as Record<string, string>,
    postularUrl: "/postular",
    postularLabel: "Enlace de postulación",
    internStatuses: {
      activo: "Activo",
      completado: "Completado",
      suspendido: "Suspendido",
    } as Record<string, string>,
    internPrograms: [
      "Psicología",
      "Terapia Ocupacional",
      "Fonoaudiología",
      "Trabajo Social",
      "Educación Diferencial",
      "Enfermería",
      "Otra",
    ],
  },
  foundationDocuments: {
    categories: {
      all: "Todas",
      manual: "Manual",
      legal: "Legal",
      politica: "Política",
      reglamento: "Reglamento",
      certificado: "Certificado",
      acta: "Acta",
      convenio: "Convenio",
      financiero: "Financiero",
      otro: "Otro",
    } as Record<string, string>,
    defaultLabels: [
      "Manual de Procedimientos",
      "Estatutos",
      "Reglamento Interno",
      "Política de Privacidad",
      "Acta de Directorio",
      "Convenio Marco",
      "Resolución Sanitaria",
      "Certificado MINSAL",
    ],
  },
  applicantForm: {
    title: "Postula a Fundación RASMA",
    subtitle: "Completa el formulario para enviar tu postulación. Te contactaremos por correo si tu perfil avanza.",
    name: "Nombre completo",
    email: "Correo electrónico",
    phone: "Número de teléfono",
    positions: "¿Qué puestos te interesan?",
    cv: "Currículum o carta de presentación",
    submit: "Enviar postulación",
    success: "Tu postulación ha sido enviada exitosamente. Te contactaremos pronto.",
  },
  audit: {
    title: "Registro de Auditoría",
    action: "Acción",
    entity: "Entidad",
    user: "Usuario",
    timestamp: "Fecha/Hora",
    details: "Detalles",
    actions: {
      create: "Crear",
      update: "Actualizar",
      delete: "Eliminar",
      view: "Ver",
      login: "Inicio de sesión",
      logout: "Cierre de sesión",
      password_reset: "Restablecimiento de contraseña",
      email_change: "Cambio de correo",
    },
  },
} as const;
